### ISSUE TITLE
Fix bug in export.py

### ISSUE THREAD

**Issue by dnak0** [relaxart/LeoPort#1]
Must be:
        if translate["is_exist"]:
            result = "Already exists: "
        else:
            result = "Add word: "

**Comment by nanodracula** [comment]
As I know "0" is coerced to false and "1" to true, so there is no mistake.

**Comment by Yur-ok** [comment]
Вы бы могли проверить работает скрипт на сегодняшний день?
Я пытался его запустить, но он выдает вот такую ошибку:
(22, "invalid mode ('r') or filename")

Верися питона 2.7 и 3.5
Но я запускал указываю версию 2.7 через утилиту "py"

PS. Я новичок и возможно что-то сделал не так. Поэтому и прошу Вас о проверке. Может на сервере Лингвалео чего поменяли?
Просто Ваша программа мне ОЙ! Как сильно нужна!
Заранее благодарю Вас!

С уважением
Юрий

**Comment by relaxart** [comment]
@Yur-ok. Ok I will try to help
https://github.com/relaxart/lingualeo.export/commit/d8ddab56e9da12ac9d121bae23d49db0c45e42ce
I updated repository. Could you check again?

**Comment by stealzy** [comment]
It need python 2.7. I think it must be mentioned in Readme.
