### ISSUE TITLE
Doesn't add worlds.

### ISSUE THREAD

**Issue by k1p1l0** [relaxart/LeoPort#11]
When I try to add the world from the .txt file, it doesn't work.
Yes, it checks words in my dictionary and login system works.

Only one time when in the file was one word, it has added. The word was 'kikikiki'.

**Comment by relaxart** [comment]
I have checked with 'kikikiki'. It could be Lingualeo issue. Could you attach the file?

**Comment by k1p1l0** [comment]
[words.txt](https://github.com/relaxart/LeoPort/files/299225/words.txt)

https://www.dropbox.com/s/6izcg1m2m93mrbq/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202016-06-05%2009.45.43.png?dl=0

It can added only one from the list
![lin](https://cloud.githubusercontent.com/assets/7171026/15804028/80d57146-2b02-11e6-86e5-cfefe2614feb.png)

Can you please give me your an example with words (in the file?)

**Comment by relaxart** [comment]
So it means you already have these words in your dictionary. Word has several translates. App chooses first popular translation for the word. That's why you see "Word added". It's a minor bug I'll fix it later.

**Comment by k1p1l0** [comment]
I haven't these worlds in the Lingualeo.

Thas why I wrote this issue down.

![2016-06-05 20 32 10](https://cloud.githubusercontent.com/assets/7171026/15807099/cea886f6-2b5c-11e6-8882-223804ff6b7b.png)

Will wait for the fix! :+1:

**Comment by msabirov** [comment]
Hi. Same mistake.

**Comment by MikhailKaduchka** [comment]
For me it happened when I ran out of meatballs. Check first that you have enough of it.
