### ISSUE TITLE
Catalina fail

### ISSUE THREAD

**Issue by Snoomy** [relaxart/LeoPort#16]
$ ./gradlew run

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '13.0.1'.

**Comment by relaxart** [comment]
Hello, @Snoomy could you, please download the new release and try again?

**Comment by relaxart** [comment]
@Snoomy I will close the issue. If something is not working properly, please create a new one. Thank you for feedback.

**Comment by Snoomy** [comment]
Successful run, but import failed (both Kinlde .db and .txt file):

"Start import to Lingualeo...
Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive"
