### ISSUE TITLE
build 17, Catalina fail

### ISSUE THREAD

**Issue by Snoomy** [relaxart/LeoPort#18]
build 17 successfully run on Catalina and Java SE Development Kit 13.0.1, but import fails (both Kinlde .db and .txt file):

"Start import to Lingualeo...
Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive"

**Comment by ElKornacio** [comment]
Same problem on the same system.

**Comment by sp3k7or** [comment]
Same on archlinux. Tried to use: java-11-openjdk,  java-13-openjdk.

**Comment by bazarus** [comment]
Same on win. I think they had changed API or smth.

**Comment by relaxart** [comment]
Hello @sp3k7or @Snoomy @ElKornacio and @bazarus, could you, please check the fix. I have updated the API calls to Lingualeo. This update should work. 
Regards!

**Comment by Snoomy** [comment]
@relaxart works for me. thanks a lot!
