### ISSUE TITLE
 при попытке обработки русского слова возникает Exception 

### ISSUE THREAD

**Issue by sch839** [relaxart/LeoPort#7]
при попытке обработки русского слова возникает Exception 

Exception in thread "Thread-5" java.lang.NullPointerException

>   at com.lingualeo.Importer.startImport(Importer.java:47)
>   at com.lingualeo.controller.FormController.lambda$handleSubmitButtonAction$0(FormController.java:29)
>   at java.lang.Thread.run(Thread.java:745)

1)имеется большой список слов
2)пару раз там проскакивают русские слова
3)при попытке его обрботать упадем с NullPointerException

**Comment by relaxart** [comment]
Fixed
